version: "3"

services:

  backend:
    build: ./
    container_name: dorsia_container
    working_dir: /dorsia
    restart: always
    command: bash -c "python dorsia/manage.py migrate --settings=dorsia.settings && python dorsia/manage.py collectstatic --noinput --settings=dorsia.settings && gunicorn -w ${WSGI_WORKERS} -b 0:${WSGI_PORT} --chdir ./dorsia dorsia.wsgi:application --log-level=${WSGI_LOG_LEVEL}"
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    volumes:
      - ./dorsia:/dorsia/dorsia
      - static_content:/dorsia/dorsia/static
    env_file:
      - .env

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/dorsia/dorsia/static
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - backend


volumes:
  static_content: { }
