version: "3"

services:
  chroma_server:
    image: ghcr.io/chroma-core/chroma:0.3.15
    volumes:
      - ./dorsia/chroma:/chroma
    command: bash -c "pip install chromadb && uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 6000"
    ports:
      - 5000:6000

  backend:
    build: ./
    container_name: dorsia_container
    working_dir: /dorsia
    restart: always
    command: bash -c "python dorsia/manage.py migrate --settings=dorsia.settings && python dorsia/manage.py collectstatic --noinput --settings=dorsia.settings && python dorsia/manage.py runserver 0:${WSGI_PORT}"
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    volumes:
      - ./dorsia:/dorsia/dorsia
      - static_content:/dorsia/dorsia/static
    env_file:
      - .env
    depends_on:
      - chroma_server

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/dorsia/dorsia/static
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8000:8000
      - 443:443
    env_file:
      - .env
    depends_on:
      - backend


volumes:
  static_content: { }
